source = ~/.config/omarchy/current/theme/hyprlock.conf

general {
    ignore_empty_input = true
}

background {
    monitor =
    color = $color
    path = ~/.config/omarchy/current/background
    blur_passes = 0
}

animations {
    enabled = true
}

input-field {
    monitor = DP-2
    size = 180, 40
    position = 0, 70
    halign = center
    valign = bottom

    inner_color = $inner_color
    outer_color = $outer_color
    outline_thickness = 4

    font_family = JetBrainsMono Nerd Font
    font_color = $font_color

    placeholder_text = Contraseña
    check_color = $check_color
    fail_text = <i>$FAIL ($ATTEMPTS)</i>

    rounding = 20
    shadow_passes = 1
    fade_on_empty = false
}

auth {
    fingerprint:enabled = false
}

#source = ~/.local/state/omarchy/toggles/hyprlock.conf
